### ISSUE TITLE
Form hidden inputs don't track data from load function

### ISSUE THREAD

**Issue by n00ki** [huntabyte/formsnap#70]
Hi :)

First and foremost, i'd like to take this opportunity to thank @huntabyte for all of his contributions to the Svelte ecosystem, including this one. your work has proven to be so meaningful for me personally and for all other Svelte enthusiasts around the world.

I'm facing an issue with a form that is supposed to be partially populated by data from the page load function:
```svelte
<script lang="ts">
	// Utils
	import type { FormOptions } from 'formsnap';
	import { reset_password_schema } from '$lib/validations/auth';
	import * as flashModule from 'sveltekit-flash-message/client';

	// Stores
	import { page } from '$app/stores';

	// Components
	import FormWrapper from '$components/FormWrapper.svelte';
	import * as Form from '$lib/components/ui/form';

	// Assets
	import { Reload } from 'radix-icons-svelte';

	export let data;

	const options: FormOptions<typeof reset_password_schema> = {
		validators: reset_password_schema,
		delayMs: 500,
		multipleSubmits: 'prevent',
		syncFlashMessage: false,
		flashMessage: {
			module: flashModule
		}
	};
</script>

<FormWrapper>
	<p class="my-1 text-start">Enter a new password for <strong>{$page.data?.email}</strong></p>
	<Form.Root
		method="POST"
		action="?/reset"
		form={data.form}
		schema={reset_password_schema}
		{options}
		let:config
		let:delayed
		debug={true}
	>
		<Form.Field name="email" {config}>
			<Form.Input type="hidden" value={data?.email ?? ''} aria-hidden="true" required />
		</Form.Field>

		<Form.Field name="token" {config}>
			<Form.Input type="hidden" value={data?.token ?? ''} aria-hidden="true" required />
		</Form.Field>

		<Form.Field name="password" {config} let:constraints>
			<Form.Label>Password</Form.Label>
			<Form.Input type="password" {...constraints} />
			<Form.Validation />
		</Form.Field>

		<Form.Field name="password_confirmation" {config} let:constraints>
			<Form.Label>Password Confirmation</Form.Label>
			<Form.Input type="password" {...constraints} />
			<Form.Validation />
		</Form.Field>

		<Form.Button disabled={delayed} variant="secondary" class="my-2 w-full">
			{#if delayed}
				<Reload class="mr-2 h-4 w-4 animate-spin" />
			{/if}
			Update Password
		</Form.Button>
	</Form.Root>
</FormWrapper>
```

as you can see in the snippet above, the `email` and `token` fields should be populated and bound to their respective `data` attributes. but, for some reason - they don't. values are there (`console.log(data)`), yet the form isn't submitting, and the formsnap debug component confirms that these fields aren't populated (empty).
I've also verified that the `Input` component's `$value` store (from `getFormField()`) is indeed empty for both fields.
am i doing something wrong? or is it  a real issue?

Thanks a lot in advance🙏

**Comment by n00ki** [comment]
a quick update:
setting the values as actual form data on the server and accessing the form on the client works.
what am is missing here...?
```ts
// +page.server.ts
...
    const form = await superValidate(reset_password_schema);

    form.data.email = 'email;
    form.data.token = 'token;

    return {
	form
    };
```
```svelte
// +page.svelte
...
    <Form.Field name="email" {config}>
	<Form.Input type="hidden" value={data?.form?.data?.email ?? ''} aria-hidden="true" required />
    </Form.Field>

    <Form.Field name="token" {config}>
	<Form.Input type="hidden" value={data.form?.data?.token ?? ''} aria-hidden="true" required />
    </Form.Field>
...
```

**Comment by n00ki** [comment]
A quick update:
Manipulating the actual form and populating it with data on the server side (not in `PageData`), then using the field `value` prop on the client works.
```ts
// +page.server.ts 
// Load Function
...
    const form = await superValidate(reset_password_schema);

    form.data.email = email_param;
    form.data.token = token_param;

    return {
	form
    };
```
```svelte
// +page.svelte
...
    <Form.Field name="email" {config} let:value>
      <Form.Input type="hidden" value={value ?? ''} aria-hidden="true" required />
    </Form.Field>

    <Form.Field name="token" {config} let:value>
      <Form.Input type="hidden" {value} aria-hidden="true" required />
    </Form.Field>
...
```
what am is missing?

**Comment by huntabyte** [comment]
Hey @n00ki, I believe this issue is fixed with the latest release. Please let me know! I am going to work on adding test cases for everything this week to ensure everything is working as expected!

**Comment by JYLN** [comment]
@huntabyte @n00ki 

It could be that I'm not understanding the above issue properly, but after some testing with the latest release, I'm still unable to get values from the returned data object to populate within an input's value.

```ts
// +page.server.ts
// Load Function
...
const form = await superValidate(formSchema);

return {
  form,
  name: 'Something'
}
``` 

```svelte
// +page.svelte
// Within <Form.Root>
...
<Form.Field {config} name="name">
	<Form.Item>
		<Form.Label>Name</Form.Label>
		<Form.Input value={data.name ?? ''} />
		<Form.Validation />
	</Form.Item>
</Form.Field>
```

With the above code, `'Something'` does not populate within the form. I believe this to be a mechanism of sveltekit-superforms; potentially to not allow any malformation of shape of the schema or types within the schema. I found a [solution within the sveltekit-superforms docs](https://superforms.rocks/get-started#populate-form-from-database) to allow the data from the load function to populate within their respective field. For the above example, I was able to get `'Something'` to populate within the input field from the load function using the following:

```ts
// +page.server.ts
// Load Function
...
const returnObj = { name: 'Something' };

const form = await superValidate(returnObj, formSchema);

return { form };
```

```svelte
// +page.svelte
// Within <Form.Root>
...
<Form.Field {config} name="name">
	<Form.Item>
		<Form.Label>Name</Form.Label>
		<Form.Input />
		<Form.Validation />
	</Form.Item>
</Form.Field>
```

With the above code, `'Something'` populates within the input field, even without the value attribute. As well, I set the above input to `type="hidden"` and the debug of the form still shows the `name` field populated. It appears that any value that is intended to be populated by a database or other external source needs to be placed into an object following the same shape as the form's schema, then passed through the `superValidate` function. I'm unsure if this information helps, but wanted to contribute to the conversation as I ran into this same issue, and was able to resolve it in this fashion based on the underlying technology of sveltekit-superforms.

**Comment by huntabyte** [comment]
You are right on the money @JYLN! This is how superforms was designed! When using the `<Form.Input />` you never need/should need to pass any `value` prop, as it will be populated with the true value in the `$form` store returned from the load function.

There is some documentation on this that can be read about [here](https://superforms.rocks/get-started#populate-form-from-database)!
